### ISSUE TITLE
Images too large

### ISSUE THREAD

**Issue by jum-s** [pipay07/site-proximite07#1]
Vos images sont très lourdes : 
Notamment les 4 photos, a descendre vers les 150ko chacune.
Le logo de lamastre est énorme également

**Comment by sandrineluquet** [comment]
Et bonjour!!!
Merci pour ce feedback.
En effet il faudra retravailler les images.
Je met en page img et textes et Maud fait le readme
Bonwe
Sandrine

**Comment by pipay07** [comment]
c'est en cours ...
